const arrayOfNames = [
  "Harlee Edge",
  "Robyn Antonio",
  "Ari Compton",
  "Skylar Pyle",
  "Alessandra McKinnon",
  "Mikaila Wiggins",
  "Fredrick Kessler",
  "Jada Brothers",
  "Dominique Painter",
  "Ayanna Trotter",
  "Adeline Magana",
  "Sheyla Cain",
  "Delilah Chavis",
  "Sienna Needham",
  "Dora Crane",
  "Jayna Starks",
  "Athena Broyles",
  "Jamie Trinh",
  "Keanna Keegan",
  "Emely Guzman",
  "Maddison Palma",
  "Rodolfo Cameron",
  "Chastity Gipson",
  "Adolfo Kimmel",
  "Zavier Marin",
  "Cole Law",
  "Lee Colvin",
  "Branden Bonilla",
  "Travion Peoples",
  "Chase Phelps",
  "Blanca Bowens",
  "Kadin Mondragon",
  "Jaeden Espinal",
  "Carley Spears",
  "Penelope Hendricks",
  "Chassidy Kumar",
  "Demetria Goodson",
  "Christin Rizzo",
  "Brook Finley",
  "Stephany Parent",
  "Kendrick Forbes",
  "Fallon Kirby",
  "Lionel Guillory",
  "Raven Strom",
  "Adrienne Hathaway",
  "Ella Benedict",
  "Dustin King",
  "Genevieve Guevara",
  "Seamus Battle",
  "Amia Clancy",
  "Alana Prather",
  "Francisca Reynoso",
  "Lexus Carroll",
  "Jalyn Altman",
  "Porter Bearden",
  "Lillian Boland",
  "Sebastien Horn",
  "Rochelle Liles",
  "Winter Liang",
  "Daria Hickey",
  "Mindy McLain",
  "Judy Santamaria",
  "Darin Denney",
  "Breana Caswell",
  "Dakota Lujan",
  "Ivette Portillo",
  "Adamaris Braun",
  "Bryana Matheny",
  "Star Power",
  "Mykala Ali",
  "Thaddeus Wolff",
  "Samuel Simpkins",
  "Humberto Lumpkin",
  "Pablo Salazar",
  "Brennon Jeffries",
  "Abdul Way",
  "Ivan Cornett",
  "Julissa Hardin",
  "Evan Connell",
  "Marquez Gilliland",
  "Dangelo Gantt",
  "Dakoda Faulkner",
  "Justyn Klein",
  "Gilberto Gunter",
  "Lexie Sharpe",
  "Stetson Shea",
  "Sky Bowman",
  "Lesly Rupp",
  "Lilly Cowart",
  "Shirley Addison",
  "Jaci Kilpatrick",
  "Grant Chavez",
  "Maryjane Johns",
  "Jericho Brothers",
  "Shayna Lockhart",
  "Blanca Packer",
  "Sincere Medlin",
  "Araceli McGovern",
  "Wilfredo Dayton",
  "Pablo Stoner",
  "Charlie Moseley",
  "Nyla Fletcher",
  "Mykala Cornell",
  "Connie Doucette",
  "Juana Bradshaw",
  "Philip Daugherty",
  "Shayne Ritchey",
  "Christy Kwon",
  "Fiona Kowalski",
  "Rohan Nicholas",
  "Jakob Swisher",
  "Alec Teague",
  "Jewel Babcock",
  "Laura Woodruff",
  "Jadon Fortune",
  "Jaylene Kovach",
  "Michael Bair",
  "Theodore Keeney",
  "Katelyn Ho",
  "Adonis Kang",
  "Bruno Stahl",
  "Tanya Majors",
  "Luc Siegel",
  "Jamison Andersen",
  "Ayleen Connors",
  "Cole Homan",
  "Andres Benitez",
  "Maryam Schaeffer",
  "Carissa Conklin",
  "Kenia Singh",
  "Lilly Barclay",
  "Christina Davies",
  "Mekhi Saenz",
  "Dakotah Berrios",
  "Tavion Bowden",
  "Joaquin Salcedo",
  "Floyd Swartz",
  "Shekinah Butler",
  "Laken Cazares",
  "Ali Jarvis",
  "Francis Daugherty",
  "Jaycob Howland",
  "Corrina Langdon",
  "Moses Barnette",
  "Kerry Lemke",
  "Ansley Delossantos",
  "Jane Cousins",
  "Asya Christman",
  "Cain Sheehan",
  "Ben Covarrubias",
  "Annalee Hyde",
  "Trenten Quinones",
  "Tyrese Sheffield",
  "Lisbeth McKenna",
  "Mikaela Sager",
  "Dario Fair",
  "Nathaniel Tomlinson",
  "Kaya Edmondson",
  "Cristian Lockett",
  "Keith Otto",
  "Kolby Dietz",
  "Santos Nugent",
  "Mandy Embry",
  "Mikaela Craven",
  "Carina Valdivia",
  "Desire Edmondson",
  "Brooklyn Willoughby",
  "Chad Angulo",
  "Octavia Guillen",
  "Jaela Hubbard",
  "Triston Wilks",
  "Rylan Pepper",
  "Aspen Pickard",
  "Amir Ceja",
  "Dajuan Tejeda",
  "Nikole Carson",
  "Max Amato",
  "Jasmin Nichols",
  "Malcolm Rees",
  "Kali Lacy",
  "Mariela Roby",
  "Roderick Demers",
  "Johnson Quarles",
  "Jesenia Longo",
  "Karen Mercado",
  "Dane Ramon",
  "Joseluis Hoyle",
  "Donavan Acker",
  "Braeden Moua",
  "Brooklyn Moran",
  "Harry Trout",
  "Tracy Baum",
  "Glen Cote",
  "Damon Kee",
  "Reynaldo Peters",
  "Dayanara Starling",
  "Monique Rowland",
  "Patricia Killian",
  "Vladimir Colon",
  "Dominick Zhu",
  "Kayle Lo",
  "Terence Layne",
  "Tianna Caraballo",
  "Troy Hawthorne",
  "Jovanny Frick",
  "Caiden Flores",
  "Natalee Harding",
  "Jade Sterling",
  "Deisy Paul",
  "Devonta McGregor",
  "Agustin Ramos",
  "Dan Abney",
  "Messiah Montoya",
  "Tracy Villasenor",
  "Jamia Locklear",
  "Savion Moua",
  "Maxim Blake",
  "Esteban Strom",
  "Billy Hatch",
  "Ayden Dobson",
  "Jacquez Witt",
  "Ingrid Yazzie",
  "Bryce Palumbo",
  "Aurora Cheatham",
  "Yajaira Rose",
  "Kendrick Cabrera",
  "Connie Marsh",
  "Marisa Mcmillen",
  "Bobbie Jewell",
  "Yessica Judge",
  "Marcel Doe",
  "Elaina Orellana",
  "Sidney Zook",
  "Coleman Villarreal",
  "Kendrick McKnight",
  "Guadalupe Lowe",
  "Nakia Bruner",
  "Sheridan Palacios",
  "Cara Frame",
  "Dakoda Espinal",
  "Lainey Yost",
  "Janie Simpkins",
  "Jordan Hester",
  "Abdul Meyers",
  "Danielle Duggan",
  "Lara Showalter",
  "Gracie Harwood",
  "Jayna Crook",
  "Margarita McDowell",
  "Stetson Joe",
  "Jacquelyn Cone",
  "Adrianne Mclemore",
  "Tristin Tatum",
  "Erick Pearce",
  "Aria Neill",
  "Jeffery Collins",
  "Greta Mathis",
  "Kobe Bagley",
  "Jarvis South",
  "Caley Payne",
  "Charles Chiu",
  "Elmer Grissom",
  "Yazmin Stark",
  "Maurice Kemper",
  "April Wallis",
  "Mary Hubbard",
  "Marie Liles",
  "Theron Sample",
  "Liberty Rust",
  "Joanna Hankins",
  "Simran Whaley",
  "Leyla Bagley",
  "Constance Terry",
  "Kelsey Jones",
  "Edmund Hammonds",
  "Ilana Colvin",
  "Kari West",
  "Braeden Phelps",
  "Jackelyn Conover",
  "Henry Gonzales",
  "Zechariah Marrero",
  "Emiliano Hoffman",
  "Emery Tubbs",
  "Stuart Parkinson",
  "Abbey Allen",
  "Kenia Caudill",
  "Coleton Murry",
  "Dania Donaldson",
  "Eliza Schweitzer",
  "Janine Stephenson",
  "Khalil Whitley",
  "Erick Quintero",
  "Ira Denton",
  "Lanie Boston",
  "Keeley Nguyen",
  "Finn Borges",
  "Tyler Ritter",
  "Lauren Toney",
  "Keandre Morin",
  "Alexys Triplett",
  "Maximilian Leary",
  "Antonio Merrell",
  "Reynaldo Bowie",
  "Nichole Lazo",
  "Leigha Battle",
  "Julie Cutler",
  "Rosa Benavides",
  "Fidel Laughlin",
  "Reese McCarty",
  "Gerald Everett",
  "Rowan Amato",
  "Rhea Newby",
  "Rogelio Crowe",
  "Aldo Cabrera",
  "Bradley Couture",
  "Maren Painter",
  "Travis Banda",
  "Kristian Kern",
  "Herman Joy",
  "Joel Zeller",
  "Kortney Schuster",
  "Elliott Keegan",
  "Domenic Mata",
  "Kelsy Schindler",
  "Braydon Barrow",
  "Rileigh Sells",
  "Giavanna Eubanks",
  "Karly Trinidad",
  "Luca Gillette",
  "Zain Loomis",
  "Monika Hill",
  "Cedric Salas",
  "Daniella Forte",
  "Jailyn Matos",
  "Jordin Sell",
  "Alan Amaro",
  "Chance Sparks",
  "Shaniya Phelan",
  "Estefani Slattery",
  "Angeles Odom",
  "Dwight Bernstein",
  "Denisse Hair",
  "Francis Schulze",
  "Esmeralda Ogden",
  "Perry Collins",
  "Makaila Kilpatrick",
  "Janessa Headley",
  "Ryan Valentine",
  "Hanna Jaeger",
  "Alberto Guinn",
  "Camren Leung",
  "Maurice Doss",
  "Cannon Coughlin",
  "Kerry Cooper",
  "Santiago Lockwood",
  "Yaquelin Ridley",
  "Megan Reeder",
  "Tye Regan",
  "Killian Phillips",
  "Damon Krebs",
  "Allysa Sorrell",
  "Jericho Kuntz",
  "Landon Salvador",
  "Sky Murphy",
  "Daveon McDonnell",
  "Jarod Mathias",
  "Rocky McClanahan",
  "Mara Jorgensen",
  "Nathanial Beaulieu",
  "Kaci Stevenson",
  "Fiona Arnold",
  "Krysten Lawler",
  "Jaron Staples",
  "Breonna Muir",
  "Gerardo Martinez",
  "Cruz Santillan",
  "Cristal Russell",
  "Shana Holliday",
  "Emmalee Calkins",
  "Infant Tom",
  "Garett Huey",
  "Alecia Jacoby",
  "Max Kincaid",
  "Ty Loya",
  "Carmen Ayres",
  "Annamarie Ennis",
  "Conrad Farrell",
  "Ishmael Washington",
  "Sterling McClelland",
  "Anjali Amaro",
  "Jazmyne Hillman",
  "Julian Joy",
  "Lorraine Levin",
  "Dylan Khan",
  "Alton Brewster",
  "Justice Huynh",
  "Marguerite Cook",
  "Myah Briseno",
  "Janae Cazares",
  "Devan Slack",
  "Kelvin Wentz",
  "Colby Poindexter",
  "Cassie Valenzuela",
  "Griffin Callahan",
  "Paige Joyner",
  "Issac Sizemore",
  "Miguel Harden",
  "Kegan Mulligan",
  "Damaris Hawks",
  "Jaxon Schaeffer",
  "Lauren Butterfield",
  "Ean Woody",
  "Darin Forte",
  "Jasmin Dang",
  "Jaret Case",
  "Zack Maddox",
  "Kiara Pressley",
  "Cherish Kent",
  "Bruce Jewell",
  "Trent Kramer",
  "Elian Munn",
  "Lea Peterman",
  "Dimitri Laws",
  "Claudio Lund",
  "Kristopher Dowell",
  "Zack Corona",
  "Jadyn Crump",
  "Muhammad Mcallister",
  "Thaddeus Linares",
  "Shianne Hamel",
  "Trista Trapp",
  "Chancellor Newby",
  "Treasure Wisniewski",
  "Amanda Santiago",
  "Matthew Elrod",
  "Brennen Dang",
  "Darin Sams",
  "Julieta Machado",
  "Raheem Paris",
  "Kerry Knudsen",
  "Bridger Merritt",
  "Marc Samuels",
  "Jaylon Cadena",
  "Enzo Padgett",
  "Austen Farris",
  "Sergio Simms",
  "Randi Schilling",
  "Jarvis Lankford",
  "Caden Augustine",
  "Louis Thrasher",
  "Todd Payne",
  "Zain Whittaker",
  "Thaddeus Werner",
  "Rylan Gifford",
  "Ivan Grubb",
  "Makala Pham",
  "Arman Lawless",
  "Isaak Kohl",
  "Parker Jacobson",
  "Ali Canada",
  "Elliott Casteel",
  "Kaitlyn Reeder",
  "Cailin Magee",
  "Kobie Bowers",
  "Steven Angeles",
  "Chester Pettit",
  "Ira Withrow",
  "Juliette Bourque",
  "Marianne Boggs",
  "Alexander Schmidt",
  "Kourtney Zielinski",
  "Leila Mattox",
  "Caleigh Cooke",
  "Hayley Cormier",
  "Graham Loera",
  "Vincent Nelson",
  "Kyle Schrader",
  "Katelynn Bone",
  "Amalia Torrez",
  "Cristian Starr",
  "Loren Page",
  "Gannon Hoover",
  "Ashley McClellan",
  "Jessalyn Jones",
  "Graham Crawford",
  "Jennifer Newcomb",
  "London Cottrell",
  "Devin Guy",
  "Monika Spence",
  "Ciara Dickson",
  "Diana Merriman",
  "Federico Farrow",
  "Colleen Marquez",
  "Asa Foley",
  "Bailey McGraw",
  "Krysta Foy",
  "Jerimiah Matos",
  "Shyann Duffy",
  "Leanne Hays",
  "Caitlyn Belcher",
  "Jacob Flanagan",
  "Ashtyn Allan",
  "Tyshawn Starnes",
  "Abigayle Parent",
  "Landen Covington",
  "Noe Anders",
  "Destinee Vandyke",
  "Devonte Roman",
  "Brad Bourne",
  "Jalon Vigil",
  "Shae Barney",
  "Skyler Covarrubias",
  "Alexandra Barker",
  "Shanna McClellan",
  "Alyse Romero",
  "Marcanthony Jacoby",
  "Adrianna Dupree",
  "Keanna High",
  "Alanna Serrano",
  "Kourtney Altamirano",
  "Keshon Newman",
  "Sidney Pierce",
  "Lindsay Haddad",
  "Micayla Pringle",
  "Cyrus Randle",
  "Janie Pereira",
  "Keagan Lanier",
  "Tye Weems",
  "Jonatan Begley",
  "Delaney Guillen",
  "Jill Church",
  "Brooklynn Beck",
  "Payne Stuckey",
  "Shelbie Hammons",
  "Ashlie Batson",
  "Federico Hollingsworth",
  "Alaysia Scarborough",
  "Nathanial Burch",
  "Alyssia Wyatt",
  "Noel Rubio",
  "Vicente Schiller",
  "Micah Gross",
  "Daphne Hanson",
  "Theo Silverman",
  "Rylee Brink",
  "Carlo Valdes",
  "Alfredo Gould",
  "Jalin Louis",
  "Gisselle Beverly",
  "Jasmyn Dang",
  "Quinn Bates",
  "Keyanna Alderman",
  "Carla Herrick",
  "Coleman Capps",
  "Rowan Brunson",
  "Vance Cornejo",
  "Jameson Buchanan",
  "Ivory Lassiter",
  "Jordon Cabrera",
  "Cristofer Dallas",
  "Griffin Stone",
  "Dalton Berrios",
  "Colin Boone",
  "Darius Bourque",
  "Rochelle Ojeda",
  "Duane Mabry",
  "Alana Neal",
  "Baby Hewitt",
  "Jaycie Stoddard",
  "Kolton Hamrick",
  "Lacy McDaniel",
  "Darien Harmon",
  "Micheal Aldrich",
  "Nolan Grier",
  "Long Gannon",
  "Omari McIntire",
  "Leo Salgado",
  "Rashawn Pratt",
  "Dashawn Bowser",
  "Camden Hulsey",
  "Darryl Sands",
  "Graciela Dodge",
  "Taylor Kay",
  "Giselle Ferris",
  "Zackery Dallas",
  "Carol Hammons",
  "Bernard Block",
  "Linda Brockman",
  "Karleigh Posey",
  "Kari Ohara",
  "Alanna Florez",
  "Coy Dewitt",
  "Devonta Gentry",
  "Shayne Ly",
  "Victoria Byrne",
  "Corinne King",
  "Markel Whitmore",
  "Jaylen Best",
  "Bayleigh Cave",
  "Felix Puckett",
  "Federico Villalobos",
  "Jada Houck",
  "Perry Temple",
  "Kolby Bliss",
  "Brent Grantham",
  "Alyson Goforth",
  "Harrison Doty",
  "Easton Pemberton",
  "Leanne Sturgeon",
  "Reese Connor",
  "Xander Cordero",
  "Bennett Petersen",
  "Tyreke Strain",
  "Bowen Dominguez",
  "Gerard Clausen",
  "Dominick Julian",
  "Edgardo Womack",
  "Kaitlynn Wiley",
  "Zavier Hewitt",
  "Sheldon Rains",
  "Kassie Delaney",
  "Kellen Rosas",
  "Arturo Ridenour",
  "Cielo Madrid",
  "Jayson Gaston",
  "Brady Forte",
  "Kenia Roby",
  "Dusty Davenport",
  "Alma Clancy",
  "Reina Ragan",
  "Pedro Epps",
  "Paxton Dallas",
  "Kenan Drake",
  "Dustyn Read",
  "Ashanti Alfonso",
  "Dina Speer",
  "Myah Cable",
  "Farrah Herring",
  "Dejuan Jacob",
  "Amaiya Cornwell",
  "Tylor Saxton",
  "Imani Wolf",
  "Dwayne Schmitz",
  "Yazmine Centeno",
  "Audra Turley",
  "Colt Stinson",
  "Christa Armendariz",
  "Treyvon Ortega",
  "Terrell Romero",
  "Rickey Alaniz",
  "Robin Ewing",
  "Rex Craig",
  "Kerri Arteaga",
  "Amiya Plunkett",
  "Princess Whitley",
  "Lexis Abernathy",
  "Taylor Shumaker",
  "Jovany Doyle",
  "Jeanette Newsome",
  "Kenya Betancourt",
  "Izaiah Agnew",
  "Georgia Banda",
  "Vladimir McCloud",
  "Christine Berger",
  "Destiney Givens",
  "Davonte Tyler",
  "Byron Silverman",
  "Terence Edge",
  "Vincent Tice",
  "Danae Oakley",
  "Iliana Noonan",
  "Zoe Webb",
  "Kadin McDonald",
  "Dora Sanford",
  "Mitchell Decker",
  "Jamel Baker",
  "Maria Clary",
  "Arjun Helm",
  "Marcella Goins",
  "Bret Marin",
  "Kirk Busch",
  "Kevin Wall",
  "Wilfredo Mcafee",
  "Hayden Lofton",
  "Jolene McNally",
  "Stephan Fair",
  "Axel Hinds",
  "Orlando Christian",
  "Dean Mancuso",
  "Khalid Boyle",
  "Raekwon Oakes",
  "Shakayla Montes",
  "Larry Hobson",
  "Kendall Palacios",
  "Devlin Barnard",
  "Clay Finn",
  "Sharon Boston",
  "Tatiana Starling",
  "Bethanie Gregory",
  "Trenten Herman",
  "Keaton Bliss",
  "Rosalie Adcock",
  "Tristen Kitchen",
  "Deandre Pace",
  "Stephen Murphy",
  "Octavio Bonilla",
  "Destini Mott",
  "Esther Ly",
  "Lane Quintero",
  "Madysen Moseley",
  "Austen Boland",
  "Alexis Lang",
  "Eliseo Pollard",
  "Iman Hanna",
  "Lexie Peck",
  "Randall Pate",
  "Ivonne Romo",
  "Eugene Barger",
  "Imani Outlaw",
  "Jeniffer Rosado",
  "Krysten Kauffman",
  "Karleigh Flint",
  "Jarett Mathis",
  "Mariela Gilbert",
  "Katheryn Fong",
  "Graham Anders",
  "Giselle Marr",
  "Ramiro Trinidad",
  "Dario Robb",
  "Annalee Toledo",
  "Jaime Beatty",
  "Harmony Hicks",
  "Johanna Boudreau",
  "Daniella Alvarado",
  "Bradley Biggs",
  "Danica Grayson",
  "Cruz Huber",
  "Essence Kerr",
  "Alannah Gamble",
  "Gisselle Mosher",
  "Antoine Spaulding",
  "Mindy Bachman",
  "Forrest Huber",
  "Elliott Lackey",
  "Vanesa Starnes",
  "Uriel Mark",
  "Kiley Queen",
  "Luisa Rosenthal",
  "Josue Gilchrist",
  "Lynette Jeffers",
  "Semaj Gillette",
  "Milena Arreola",
  "Saul Fahey",
  "Ean Oshea",
  "Karly Albrecht",
  "Brittany Ferry",
  "Mahogany Noyes",
  "Leigha Garnett",
  "Kai Callahan",
  "Jon Keck",
  "Maddison Smoot",
  "Belen Browning",
  "Micayla Parr",
  "Jaliyah Arteaga",
  "Humberto Alderman",
  "Eileen Wynne",
  "Spencer Downey",
  "Neil Noyes",
  "Harvey Gonzales",
  "Dimitri Westfall",
  "Quinn McCray",
  "Jarrod Zapata",
  "Katlin Foote",
  "Neo Sebastian",
  "Jair Clemons",
  "Felix Trammell",
  "Annika Swartz",
  "Aracely Craven",
  "Mohamed Stevens",
  "Brooklyn Minton",
  "Darius Layne",
  "Elias Saldana",
  "Efren Morton",
  "Franklin Amaral",
  "Berenice Baggett",
  "Ally Julian",
  "Analisa Brockman",
  "Donavon Stinson",
  "Xzavier Rowley",
  "Jerod Dallas",
  "Kelley Tang",
  "Isaac Day",
  "Beatriz Blankenship",
  "Keagan Schultz",
  "Marguerite Chavez",
  "Dandre Cordell",
  "Devonte Branch",
  "Blaze Creech",
  "Jerome Hutcheson",
  "Deontae Hook",
  "Kyla Bernard",
  "Magaly Whalen",
  "Leonel Clary",
  "Efrain Dunning",
  "Ebony Lightfoot",
  "Taylor Cobb",
  "Ansley Medlin",
  "Cydney Walter",
  "Cristobal Seward",
  "Sarai Coles",
  "Tanner Loyd",
  "Raphael Haynes",
  "Cora Lange",
  "Brannon Bermudez",
  "Dixie Michaud",
  "Jillian Heck",
  "Kirk Irvine",
  "Sonya Brothers",
  "Kyree Bryan",
  "Miranda Ontiveros",
  "Savana Poole",
  "Kent Keck",
  "Reagan Craddock",
  "Ramsey Serna",
  "Daniel Santana",
  "Lesley Head",
  "Alessandro Sample",
  "Ingrid Keane",
  "Kade McLaughlin",
  "Bryanna Morales",
  "Calli Gardiner",
  "Darin Shipman",
  "Monique Maher",
  "Kenyon Brink",
  "Kobie Head",
  "Analise Hemphill",
  "Izaiah Wilcox",
  "Michael Neuman",
  "Kia Durbin",
  "Yamilet Montoya",
  "Janette Waldron",
  "Laney Stevenson",
  "Armani Sanborn",
  "Jacques Cohn",
  "Wyatt Schoen",
  "Paxton Ritchey",
  "Baylie Donahue",
  "Javion Cervantes",
  "Julianna Stack",
  "Adamaris Toth",
  "Keon Weatherford",
  "Brian Delossantos",
  "Alaina Spears",
  "Derick Schumacher",
  "Dashaun Damico",
  "Wilfredo Joiner",
  "Keshon Long",
  "Savanna Springer",
  "Kaliyah Danielson",
  "Adolfo Lackey",
  "Maeve Jolley",
  "Terence Falk",
  "Caelan Knowles",
  "Demetrius Hawkins",
  "Sienna Villegas",
  "Estrella Ray",
  "Octavio Haller",
  "Miriam Carrington",
  "Ali Lanham",
  "Callista Windham",
  "Braiden Blackmon",
  "Diana Cardenas",
  "Jayleen Moua",
  "Zain Sylvester",
  "Dalia Swisher",
  "Brayden Schreiber",
  "Alexandro Lucas",
  "Omari Hood",
  "Sahara Custer",
  "Darnell Burroughs",
  "Kacie Caputo",
  "Stephanie Dye",
  "Jackson Fisk",
  "Kegan Torrez",
  "Tierra Power",
  "Bradford Crooks",
  "Jaylon Walters",
  "Rhea Vickery",
  "Rigoberto Potter",
  "Junior Huerta",
  "Jarrett McGinnis",
  "Ashlie Mackey",
  "Ayesha Hanlon",
  "Xavier Lester",
  "Guillermo Layton",
  "Rylie Couch",
  "Gilberto Portillo",
  "Jovani McNamara",
  "Paxton Bobo",
  "Omar Tam",
  "Dallin Louis",
  "Aniya Holcomb",
  "Uriah Daigle",
  "Tara Wertz",
  "Dominic See",
  "Shemar Whittaker",
  "Adrien Dickinson",
  "Jakobe Clay",
  "Trenton Shanahan",
  "Katheryn Breeden",
  "Zayne Knutson",
  "Mariah Florez",
  "Latavia Hearn",
  "Genaro Kiefer",
  "Azaria Brito",
  "Ezekiel Benjamin",
  "Emilia Frame",
  "Brenna Hamm",
  "Jamie Espinosa",
  "Dorian Turk",
  "Brandan Bailey",
  "Kali Wharton",
  "Jacob Schubert",
  "Turner Lucas",
  "Marquis Knox",
  "Jared Bock",
  "Daniel Moffitt",
  "Chyanne Allison",
  "Shea Chisholm",
  "Wesley Hannon",
  "Ruben Alfonso",
  "Semaj Cordell",
  "Kirsten Cano",
  "Janessa Walker",
  "Kathy Thai",
  "Rocio Jay",
  "Dyllan Hancock",
  "Aidan Spivey",
  "Griffin Cano",
  "Luz Andrew",
  "Estrella Kaufman",
  "Mira Meyer",
  "Charlize Valenzuela",
  "Haylie Richter",
  "Maryam McRae",
  "Devan Tate",
  "Krysten Crook",
  "Zayne Earley",
  "Ajay Farrell",
  "Shakayla Carrington",
  "Breeanna Tanner",
  "Ivy Lambert",
  "Stefanie Metz",
  "Bill Botello",
  "Jalon McMahon",
  "Jakobe Mattson",
  "Ronan Leone",
  "Jericho Hutchins",
  "Emely Needham",
  "Marion Vega",
  "Iyana Starks",
  "Cooper Cardwell",
  "Cornelius Slattery",
  "Elisha Simon",
  "Madisyn Willoughby",
  "Danielle Pagano",
  "Rocky Dickey",
  "Brendan Mcfarlane",
  "Katia Eddy",
  "Candice Santamaria",
  "Stanley Lemke",
  "Shemar Nash",
  "Isabelle Reimer",
  "Kendall Rizzo",
  "Daisha Dick",
  "Rigoberto Kim",
  "Noe Miranda",
  "Skylar Conroy",
  "Mitchel Cox",
  "Deshawn Douglas",
  "Stevie Buckner",
  "Ireland Reece",
  "Mikaila Jett",
  "Madeleine Curtin",
  "Javonte Gunter",
  "Lesli Worden",
  "Shanya Bigelow",
  "Vera Marcus",
  "Andy Bowden",
  "Terrell Kyle",
  "Marion Culp",
  "Eleazar Duarte",
  "Conrad Malik",
  "Jayme Willett",
  "Annika Fierro",
  "Suzanne Bergstrom",
  "Lana Lyon",
  "Noemi Doan",
  "Lilia Colon",
  "Chana Asbury",
  "Kristi Weeks",
];

const arrayOfProfessions = [
  "Accountant",
  "Architect",
  "Artist",
  "Astronaut",
  "Biologist",
  "Bricklayer",
  "Business Analyst",
  "Carpenter",
  "Chef",
  "Chemical Engineer",
  "Civil Engineer",
  "Computer Programmer",
  "Construction Manager",
  "Consultant",
  "Dentist",
  "Dietitian",
  "Electrician",
  "Emergency Medical Technician",
  "Engineer",
  "Event Planner",
  "Financial Advisor",
  "Graphic Designer",
  "Healthcare Administrator",
  "Human Resources Manager",
  "Industrial Designer",
  "Interpreter",
  "Journalist",
  "Laboratory Technician",
  "Librarian",
  "Marketing Manager",
  "Massage Therapist",
  "Mechanic",
  "Medical Researcher",
  "Nurse",
  "Nutritionist",
  "Optometrist",
  "Painter",
  "Paramedic",
  "Pharmacist",
  "Photographer",
  "Physical Therapist",
  "Pilot",
  "Plumber",
  "Police Officer",
  "Professor",
  "Project Manager",
  "Public Relations Specialist",
  "Real Estate Agent",
  "Registered Nurse",
  "Research Scientist",
  "Sales Manager",
  "Social Worker",
  "Software Developer",
  "Statistical Analyst",
  "Teacher",
  "Technical Writer",
  "Therapist",
  "Translator",
  "Travel Agent",
  "Veterinarian",
  "Web Developer",
  "Writer",
  "Zoologist",
  "Actuary",
  "Aeronautical Engineer",
  "Archaeologist",
  "Art Director",
  "Athlete",
  "Chemical Technician",
  "Civil Rights Lawyer",
  "Clinical Psychologist",
  "Counselor",
  "Data Analyst",
  "Environmental Scientist",
  "Film Director",
  "Financial Planner",
  "Fitness Trainer",
  "Forensic Scientist",
  "Geneticist",
  "Historian",
  "Insurance Agent",
  "Journalism Professor",
  "Landscape Architect",
  "Lawyer",
  "Market Research Analyst",
  "Marine Biologist",
  "Museum Curator",
  "Network Administrator",
  "Occupational Therapist",
  "Personal Chef",
  "Philanthropist",
  "Production Assistant",
  "Quality Assurance Specialist",
  "Real Estate Broker",
  "Research Analyst",
  "School Counselor",
  "SEO Specialist",
  "Speech Pathologist",
  "Tax Advisor",
  "Theater Director",
  "Urban Planner",
  "Video Game Designer",
];
let averagePrice = 0;
function genName() {
  const arraylength = arrayOfNames.length;
  const index = Math.floor(Math.random() * arraylength + 1);
  const Name = arrayOfNames[index];
  return Name;
}

function genProfession() {
  const arraylength = arrayOfProfessions.length;
  const index = Math.floor(Math.random() * arraylength + 1);
  const Job = arrayOfProfessions[index];
  return Job;
}

function genPrice() {
  const cost = (Math.floor(Math.random() * 10) % 10) * 10 + 20;
  return cost;
}

function genPerson() {
  const person = {};
  person.name = genName();
  person.profession = genProfession();
  person.price = genPrice();
  return person;
}

const arrayOfPersons = [genPerson(), genPerson(), genPerson()];

function populateList() {
  const firstSpot = arrayOfPersons[0];
  const secondSpot = arrayOfPersons[1];

  arrayOfPersons[2] = secondSpot;
  arrayOfPersons[1] = firstSpot;
  arrayOfPersons[0] = genPerson();
}

function render() {
  populateList();
  const $freelancers = arrayOfPersons.map((person) => {
    const $row = document.createElement("tr");

    const $freelancername = document.createElement("td"); //turns name into HTML
    $freelancername.textContent = person.name;

    const $freelancerprofession = document.createElement("td"); //turns job into HTML
    $freelancerprofession.textContent = person.profession;

    const $freelancerprice = document.createElement("td"); //turns price into HTML
    $freelancerprice.textContent = "$" + person.price; //adds $ to price

    $row.appendChild($freelancername);
    $row.appendChild($freelancerprofession);
    $row.appendChild($freelancerprice);
    return $row;
  });

  const $freelancerList = document.querySelector(".freelancers");
  $freelancerList.replaceChildren(...$freelancers);

  const priceOne = parseInt(arrayOfPersons[0].price);
  const priceTwo = parseInt(arrayOfPersons[1].price);
  const priceThree = parseInt(arrayOfPersons[2].price);

  let average = (priceOne + priceTwo + priceThree) / 3;
  average = average * 100;
  average = Math.floor(average);
  average = average / 100;

  const $freelancerAverage = document.querySelector(".avg");
  $freelancerAverage.textContent = "Average Freelancer Price: $" + average;
}
render();

setInterval(() => {
  render();
}, 5000);
